name: Run Contract Linter
on:
  workflow_dispatch:
  pull_request:
jobs:
  run_contract_linter:
    name: Contract linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Install packages
        run: yarn install --non-interactive --frozen-lockfile && yarn build

      - name: Run linter
        run: yarn lint-contracts
