name: Run Tests With Gas Profiler
on:
  workflow_dispatch:
  pull_request:
jobs:
  gas_profiler:
    name: Gas profiler
    runs-on: ubuntu-latest
    env:
      COINMARKETCAP_API_KEY: b52b18a2-d44f-4646-9949-0eb0e9c68574
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Install packages
        run: yarn install --non-interactive --frozen-lockfile && yarn build

      - name: Measure
        run: yarn gas
